version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flowly_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flowly-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: flowly_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      
      JWT_SECRET: ${JWT_SECRET}
      
      RESEND_API_KEY: ${RESEND_API_KEY}
      UPLOADTHING_SECRET: ${UPLOADTHING_SECRET}
      UPLOADTHING_APP_ID: ${UPLOADTHING_APP_ID}
      UPLOADTHING_TOKEN: ${UPLOADTHING_TOKEN}
      
      NEXT_APP_PUBLIC_URL: ${NEXT_APP_PUBLIC_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - flowly-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: flowly_frontend
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      
      UPLOADTHING_SECRET: ${UPLOADTHING_SECRET}
      UPLOADTHING_APP_ID: ${UPLOADTHING_APP_ID}
      UPLOADTHING_TOKEN: ${UPLOADTHING_TOKEN}
    depends_on:
      - backend
    networks:
      - flowly-network

volumes:
  postgres_data:

networks:
  flowly-network:
    driver: bridge